name: Create a flutter build release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v4.6.0
              with:
                  java-version: "21"
                  cache: "gradle"
                  distribution: "temurin"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2.18.0
              with:
                  channel: "stable"
                  flutter-version: "3.27.1"
                  cache: true
                  # optional parameters follow
                  cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
                  cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
                  pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
                  pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

            - name: Get packages
              run: flutter pub get

            - name: Build APK
              run: flutter build apk --release --split-per-abi

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: "build/app/outputs/flutter-apk/*.apk"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release_name: "Release APK"
                  tag: v0.0.${{ github.ref }}
                  release_body: "Release APK"
                  draft: false
                  prerelease: false
