name: Create a flutter build release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Flutter
              uses: subosito/flutter-action@v2.18.0
              with:
                  flutter-version: "3.27.1"

            - name: Get packages
              run: flutter pub get

            - name: Build APK
              run: flutter build apk --release --split-per-abi

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: "build/app/outputs/flutter-apk/*.apk"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release_name: "Release APK"
                  tag: v0.0.${{ github.ref }}
                  release_body: "Release APK"
                  draft: false
                  prerelease: false
